# Generated by Django 4.2.11 on 2024-03-27 16:44

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=123, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_year', models.CharField(blank=True, default=2024, max_length=255, null=True)),
                ('attendance_month', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_day', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_name', models.CharField(blank=True, max_length=220, null=True, unique=True)),
                ('rate', models.IntegerField(blank=True, default=15, null=True)),
                ('cycle_period_start', models.DateField(max_length=255, unique=True)),
                ('cycle_period_end', models.DateField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telephone', models.IntegerField(blank=True, default=0, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('application_fee', models.IntegerField(blank=True, default=10000, null=True)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Ordinary', 'Ordinary')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PayingLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('total_paid', models.IntegerField(blank=True, default=0)),
                ('balance', models.IntegerField(blank=True, default=0)),
                ('loan_status', models.CharField(blank=True, choices=[('RUNNING', 'RUNNING'), ('SETTLED', 'SETTLED')], default='RUNNING', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=220, null=True)),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('social_fund', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('openn', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='savingsapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='LookupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(max_length=220)),
                ('Lookup_Name', models.ForeignKey(max_length=220, on_delete=django.db.models.deletion.CASCADE, to='savingsapp.lookup')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('interest_rate', models.IntegerField(default=0)),
                ('loan_period', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_status', models.CharField(blank=True, choices=[('RUNNING', 'RUNNING'), ('SETTLED', 'SETTLED')], default='RUNNING', max_length=100, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=220, null=True)),
                ('name', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='savingsapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Role', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Ordinary', 'Ordinary')], default='Admin', max_length=250, null=True)),
                ('full_name', models.CharField(blank=True, default='Name', max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, default='sacco@gmail.com', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
