# Generated by Django 3.2 on 2024-03-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0002_auto_20240328_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
